config/routes.rb
Rails.application.routes.draw do

  resources :kinds, only: [:index, :show]
  resources :snippets

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root 'snippets#index'

end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :snippets, dependent: :nullify

  validates :name, presence: true
  validates :name, uniqueness: {case_sensitive: false}
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :kind
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :work,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :snippets, dependent: :nullify

  validates :email, presence: true, uniqueness: true,
            format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user

end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  def index
    @kinds = Kind.all
  end

  def show
    @kind    = Kind.find params[:id]
    @snippets = @kind.snippets
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in"
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end


end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_snippet, only: [:show,:edit,:update,:destroy]

  def index
    @snippets = Snippet.all
  end

  def show
  end

  def new
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new snippet_params
    @user = current_user
    @snippet.user = @user
    if @snippet.save
      redirect_to @snippet, notice: "Snippet Added"
    else
      flash.now[:alert] = "Snippet was not saved..."
      render :new
    end

  end

  def edit
  end

  def update
    if @snippet.update snippet_params
      redirect_to @snippet, notice: "Snippet Updated"
    else
      flash.now[:alert] = "Snippet was not updated..."
      render :edit
    end
  end

  def destroy
    @snippet.destroy
    redirect_to snippets_path, notice: "Snippet Deleted Successfully"
  end

  private

  def snippet_params
    params.require(:snippet).permit(:title, :work, :kind_id, :private)
  end

  def find_snippet
    @snippet = Snippet.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created"
    else
      flash.now[:alert] = "Account creation failed"
      render :new
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true,
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/kinds/index.html.erb
<h1>Snippets by Kind</h1>
<div>
  <% @kinds.each do |kind| %>
    <li><%= (kind.snippets.count) > 0 ? (link_to kind.name, kind_path(kind)) : (kind.name) %> (<%= kind.snippets.count %> Snippets)</li>
  <% end %>
</div>

app/views/kinds/show.html.erb
<h1><%= @kind.name %> Snippets</h1>
<div>
  <% @snippets.each do |snippet| %>
    <li><%= link_to snippet.title, snippet_path(snippet) %></li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeSnippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Snippets", snippets_path  %>
|
<%= link_to "Snippets by kind", kinds_path  %>
|
<% if user_signed_in? %>
    Hello <%= current_user.email %> =>>
    <%= link_to "Add a snippet", new_snippet_path  %>
    |
    <%= link_to "Logout", sessions_path, method: :delete,
             data: {confirm: "are you sure you want to log out?"}%>
  <% else %>
    <%= link_to "Login", new_session_path %> |
    <%= link_to "Sign Up", new_user_path %>
  <% end %>


<hr>
  <%= notice || alert %>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<% if @snippet.errors.any? %>
  <ul>
    <% @snippet.errors.full_messages.each do |message| %>
      <li>
      <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>



<%= form_for @snippet do |f| %>
  <div>
    <%= f.label :kind %>
    <%= f.collection_select :kind_id, Kind.order(:name), :id, :name %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :work %>
    <%= f.text_area :work, rows: 20 %>
  </div>
  <div>
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<%= render "form" %>

app/views/snippets/index.html.erb
<h1>Snippets</h1>
<div>
  <% @snippets.each do |snippet| %>
    <li><%= link_to snippet.title, snippet_path(snippet) %></li>
  <% end %>
</div>

app/views/snippets/new.html.erb
<%= form_for @snippet do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :work %>
    <%= f.text_area :work, rows: 20 %>
  </div>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/snippets/show.html.erb
<p>Kind: <%= @snippet.kind.name %></p>
<p>Author: <%= @snippet.user.email %></p>
<p>Private: <%= @snippet.private %></p>
<p>Title: <%= @snippet.title %></p>
<p>Work: <%= markdown(@snippet.work)%></p>
<%= link_to "Edit", edit_snippet_path(@snippet) %>
<%= link_to "Delete", snippet_path(@snippet),
                      method: :delete,
                      data: {confirm: "Are you sure you want to delete #{@snippet.title}?"} %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li>
      <%= message %>
      </li>
    <% end %>
  </ul>
<% end %>



<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Create Account" %>

<% end %>